### ISSUE TITLE
Example-input.csv file sharing

### ISSUE THREAD

**Issue by rdcm** [indy-singh/StringsAreEvil#5]
Can you share `example-input.csv` for running samples?

```
System.IO.FileNotFoundException: 'Could not find file '...\StringsAreEvil\StringsAreEvil\example-input.csv'.'
```

**Comment by indy-singh** [comment]
Hi @rdcm, 

You can find the code to generate the input file [here](https://gist.github.com/indy-singh/f10b76c4a00e807625f9b5a8d1989772).

Thanks,
Indy
