### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [indy-singh/StringsAreEvil#6]
First, thanks for building this and posting the blogs about it!

Second, do you have a license selected for this repository? Currently it's "All Rights Reserved" in most places. Quoting from https://choosealicense.com/no-permission/
> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation.

Would you be open to adding the MIT (or similar) license to this repository?

Thanks!
🎩

**Comment by indy-singh** [comment]
Done: https://github.com/indy-singh/StringsAreEvil/commit/bc2241dbee7cb263f21dec4218fd459662356025

Cheers,
Indy

**Comment by BigBlueHat** [comment]
Thanks for adding that @indy-singh! Much appreciated. 😺

**Comment by indy-singh** [comment]
No worries @BigBlueHat - just curious are you planning on doing anything particular post-license?

**Comment by BigBlueHat** [comment]
Not replace it. 😁 Unlicensed code is scary/risky, so it was either replace it (in some existing code I'm "inheriting") or ask for a license clarification. The license clarification (thank you again!!) save the day and means we don't have to find another option. Much appreciated!!

**Comment by indy-singh** [comment]
This code wasn't meant to be used in production. I definitely don't
recommend it!

Indy

**Comment by BigBlueHat** [comment]
Great to know!! We'll start looking for another option. Appreciate the heads up!
